language: node_js
node_js:
  - '6'
sudo: required
dist: trusty

env:
- RTORRENT_SOCKET=$HOME/rtorrent/rpc.socket

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y rtorrent tmux
- npm install -g eslint istanbul

before_script:
- mkdir -p ~/rtorrent/{session,downloads,watch}/
- cp .travis/.rtorrent.rc ~
- tmux new-session -s rt -n rtorrent -d rtorrent

script:
- npm run -s lint
- npm test

after_success:
  - 'istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage'

notifications:
  slack:
    secure: Hll33nzbv81Y/YRt0Hr0YoYUhozxuS4wqYGe0eGgvtxufscBI0eX+B5VQ01c75QfuZbGbhGvoyWaP4apFfx8z7tcSJDfszdLjTrUZTgMEOZm0eb3T5Hp0qjPtVd62Wmw35J2qRoGtx3RvnpF1iAlhy8GVnH8e8JtUOpPEHYPkcfwT7vybELS4lmCZ9p87kqxqTztn07huzD9rzU+csdQoXESJZnCtlS+UJo7wktTfpvBP8McDRmtIrduJ31+EQnp2fR1ygT5Tw1CFRFOPUEkk3F5yThk8ujdsdZoVOz35BOeVJs0qoKUY8cG/Jwl6YQRiG5f+x1RTK+0QwztiU1RFS5MgEajwJ8i3KMxjoTAOnp0PX8YplUkP2DpJ2J+HA1EJrA+r97QfbDFDFkvT9+3ktFVBTbpzahM/8OY68dRN/dk8229+3YlfEEM2Lc+j9UnpXJQj2dozRsrylTAOenuucfYxkKPhAuG8mci0Akt62dmQwgEqU/amSSW/gJskYWWpDbbcAYXMLys/OhISEj+6aMLFUuoY53ShcDDzjdamBQaEiPUyGR3tdZ6q26Qni+5GM6vIx/HAHuLfQUX9vY//qLiPOZjHjjiIuW2TqbRAQnvuG5wbmnb0sab/beY7DmAEoyYPokyRDMuZbqqsXc7l45P9vAxeJkNK4zq42oLG1k=
